[username]
style_user = "blue bold"
style_root = "white bold"
show_always = true
disabled = false

[directory]
style = "green bold"
truncate_to_repo = false

[shell]
disabled = false
fish_indicator = "ğŸŸ"
